apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-mysql
  labels:
    app: mysql
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/mysql
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: mysql