apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-nginx
  labels:
    app: nginx
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/nginx
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nginx