apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-registry
  labels:
    app: registry
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/registry
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: registry