apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  type: ClusterIP
 #type: NodePort
  selector:
     app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    #nodePort: 30080